/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package listengine;


import Database.SQLiteHelper;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import listengine.controlers.ViewControler;
import listengine.models.ArmyList;
import listengine.models.DataObj;
import listengine.models.Item;
import listengine.models.Model;
import listengine.models.Unit;


/**
 *
 * @author Andreas
 */
public class GuiMain extends javax.swing.JFrame {
    
    private ViewControler controler;
    /**
     * Creates new form GuiMain
     */
    public GuiMain() {
        initComponents();
        alignt_center();//centrerar
        controler = new ViewControler();
        init();
        //--test
      
        //System.out.println(unit.getName()+"\n"+unit.getTotal()+"\n"+unit.getItem(0).getName());
       /*
        ArmyList list = new ArmyList();
        list.addUnit(unit);
        
        Model m2 = new Model("Slayer",10);
        Unit u2 = new Unit(m2);
        u2.setUnitSize(10);
        Item i2 = new Item("Great Weapon",1);
        u2.addItem(i2);
        
        list.addUnit(u2);
   
        for(int i = 0 ; i < list.getAllUnit().size(); i++){
            Unit u = list.getUnit(i);
            System.out.println(u.getUnitSize()+"st "+u.getName() + " total points: " + u.getTotal()+ " with: "+u.getItem(0).getName());
        }
        
        System.out.println("total: "+list.get_total());
        *//*
        SQLiteHelper db = new SQLiteHelper();
        
        db.insert("Dwarf Warrior", "core", 8, "models",10,10,10);
        db.insert("Dwarf Thunderers", "core", 10, "models",10,10,10);
        db.insert("Dwarf Warrior", "core", 8, "models",10,10,10);
        
        db.insert("Axe", "weapon", 18, "items");
        db.insert("Double axe", "weapon", 2, "items");
        db.insert("Double axe", "weapon", 2, "items");
        
        db.delete("Axe", "items");
        
        //testa select satsern
        
        DataObj ob = db.get_row_model("Dwarf Thunderers", "models");
        
        DataObj ob2 = db.get_row_items("Double axe", "items");
        
        
        
        
        //testar att skapa en unit med kommandrupp
        Model newModel = new Model(ob.name,ob.cost,ob.champion_cost,ob.standard_cost,ob.musicna_cost);//av thunderers
        Item newItem = new Item(ob2.name, ob2.cost);//warriors items
        Unit newUnit = new Unit(newModel);
        newUnit.addItem(newItem);
        newUnit.setUnitSize(10);
        newUnit.uppdateUnitCommand(false, false, true);
        //visar resultatet
        System.out.println("name : "+newUnit.getName() + "\ngear:  "+ newUnit.getItem(0).getName()+" cost: "+
                newUnit.getItem(0).getCost()*newUnit.getUnitSize()+"pts"+"\nsize: "+newUnit.getUnitSize()+
                "\ncomand: "+newUnit.getchamp() + "\nTotal:  "+newUnit.getTotal());
        */
        //--test
     
    }
    
    /**
     * Centrerar fönstret på skärmen
     */
    private void alignt_center(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int)((dim.getWidth() - this.getWidth())/2);
        int y = (int)((dim.getHeight() - this.getHeight())/2);
        this.setLocation(x,y);
    }
    
    /**
     * Uppdates gui lists etc
     */
    private void uppdate(){
        
    }
    
    /**
     * prepare and fill lists
     */
    private void init(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAvailable = new javax.swing.JList();
        jButtonSelectEntry = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCurrent = new javax.swing.JList();
        jButtonRemoveCurrent = new javax.swing.JButton();
        jButtonShowDetails = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelSelectedCostomize = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButtonAddItem = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonRemoveItem = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        totalLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemSaveList = new javax.swing.JMenuItem();
        jMenuItemSaveAsHTML = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemOpenList = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSkrivUt = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemDB = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemHelp = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("List Engine - an Engineers guild's creation");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Available Entries", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 10))); // NOI18N

        jScrollPane2.setViewportView(jListAvailable);

        jButtonSelectEntry.setText("Select Entry");
        jButtonSelectEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectEntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jButtonSelectEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonSelectEntry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );

        jTextArea.setEditable(false);
        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextArea.setForeground(new java.awt.Color(75, 75, 75));
        jTextArea.setRows(2);
        jTextArea.setText("Message Log");
        jScrollPane1.setViewportView(jTextArea);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 10))); // NOI18N

        jScrollPane3.setViewportView(jListCurrent);

        jButtonRemoveCurrent.setText("Remove");
        jButtonRemoveCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveCurrentActionPerformed(evt);
            }
        });

        jButtonShowDetails.setText("Show Details");
        jButtonShowDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButtonRemoveCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonShowDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemoveCurrent)
                    .addComponent(jButtonShowDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Costomize Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 10))); // NOI18N

        jLabelSelectedCostomize.setText("Selected unit");

        jScrollPane4.setViewportView(jList1);

        jButtonAddItem.setText("Add Item");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonRemoveItem.setText("Remove Item");

        jScrollPane5.setViewportView(jList2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonRemoveItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRemoveItem))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabelSelectedCostomize))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonAddItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSelectedCostomize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        totalLabel.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(255, 0, 0));
        totalLabel.setText("total");

        jButton1.setText("Save List");

        jButton2.setText("New List");

        jButton3.setText("View List");

        jMenu2.setText("File");

        jMenuItemSaveList.setText("Save List");
        jMenuItemSaveList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveListActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSaveList);

        jMenuItemSaveAsHTML.setText("Save as HTML");
        jMenuItemSaveAsHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveAsHTMLActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSaveAsHTML);
        jMenu2.add(jSeparator4);

        jMenuItemOpenList.setText("Open List file");
        jMenuItemOpenList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenListActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemOpenList);
        jMenu2.add(jSeparator5);

        jMenuItemSkrivUt.setText("Skriv ut");
        jMenuItemSkrivUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSkrivUtActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSkrivUt);
        jMenu2.add(jSeparator3);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemExit);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Database");

        jMenuItemDB.setText("Add model to database");
        jMenuItemDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDBActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemDB);

        jMenuItem1.setText("Delete model from database");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem3.setText("Add Item to database");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Delete Item from database");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenuHelp.setText("Help");

        jMenuItemHelp.setText("Help");
        jMenuItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHelpActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemHelp);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        //visar dialogruta om vi vill spara eller inte ifall vi har nånting i listorna
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemSaveAsHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveAsHTMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSaveAsHTMLActionPerformed

    private void jMenuItemSaveListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSaveListActionPerformed

    private void jMenuItemSkrivUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSkrivUtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSkrivUtActionPerformed

    private void jMenuItemOpenListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemOpenListActionPerformed

    /**
     * Databas menyvalet : add to database
     * @param evt 
     */
    private void jMenuItemDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDBActionPerformed
        //Startar upp inmatningsläget för databasen
        controler.start_db_input_model();
    }//GEN-LAST:event_jMenuItemDBActionPerformed

    /***
     * Hjälp i meny
     * @param evt 
     */
    private void jMenuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpActionPerformed
        // TODO add your handling code here:
        controler.start_help();
    }//GEN-LAST:event_jMenuItemHelpActionPerformed

    /***
     * Delete model från databasen
     * @param evt 
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        controler.start_db_del_model();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * add item from database
     * @param evt 
     */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        controler.start_db_input_item();
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    /**
    * delete item from database
    * @param evt 
    */
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        controler.start_db_del_item();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * Select klicked list objekt
     * @param evt 
     */
    private void jButtonSelectEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSelectEntryActionPerformed

    /**
     * Remove that object in your list
     * @param evt 
     */
    private void jButtonRemoveCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveCurrentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoveCurrentActionPerformed

    /**
     * Show details in your list
     * @param evt 
     */
    private void jButtonShowDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShowDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
            /*
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("com.jtattoo.plaf.smart.SmartLookAndFeel".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            */
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAddItem;
    private javax.swing.JButton jButtonRemoveCurrent;
    private javax.swing.JButton jButtonRemoveItem;
    private javax.swing.JButton jButtonSelectEntry;
    private javax.swing.JButton jButtonShowDetails;
    private javax.swing.JLabel jLabelSelectedCostomize;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jListAvailable;
    private javax.swing.JList jListCurrent;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemDB;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemHelp;
    private javax.swing.JMenuItem jMenuItemOpenList;
    private javax.swing.JMenuItem jMenuItemSaveAsHTML;
    private javax.swing.JMenuItem jMenuItemSaveList;
    private javax.swing.JMenuItem jMenuItemSkrivUt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
